substitutions:
  # main prefix for all entities
  name: "Water Heater"
  # name of your node
  node_name: "water-heater"
  # use "esp12e" for iot-uni-dongle, "esp8285" for coolrf-heatstick, or your own if you know it
  board: "esp12e"
  # time platform: "sntp" or "homeassistant"
  time_platform: "sntp"
  # SSID of your wifi
  wifi_ssid: !secret wifi_ssid
  # password of your wifi
  wifi_password: !secret wifi_password
  # password for fallback wifi hotspot
  wifi_ap_password: !secret wifi_ap_password
  # version of ewh
  ewh_version: "master"

# please do not change packeages order it is very important, just comment/uncomment
packages:
  # required package, do not comment
  ewh: github://vm03/esphome-ewh/ewh-pkg-ewh.yaml@$ewh_version

  ## optional package, uncomment next line to enable additional diagnostic clock sensor
  # clock: github://vm03/esphome-ewh/ewh-pkg-clock.yaml@$ewh_version

  ## optional package, uncomment next line to enable additional diagnostic timer sensor
  # timer: github://vm03/esphome-ewh/ewh-pkg-timer.yaml@$ewh_version

  ## optional package, uncomment next line to enable standalone web ui
  # web: github://vm03/esphome-ewh/ewh-pkg-web.yaml@$ewh_version

  ## optional package, uncomment next line to enable experimental cloud support
  # cloud: github://vm03/esphome-ewh/ewh-pkg-cloud.yaml@$ewh_version

  # required package, do not comment
  core: github://vm03/esphome-ewh/ewh-pkg-core.yaml@$ewh_version
